# XXX this file is automatically generated.
self: super:
let
  inherit (super) callPackage;
in {
  ansi-styles = callPackage ./ansi-styles {};
  async-foreach = callPackage ./async-foreach {};
  bindings = callPackage ./bindings {};
  callsites = callPackage ./callsites {};
  chartjs-color-string = callPackage ./chartjs-color-string {};
  color-convert = callPackage ./color-convert {};
  color-name = callPackage ./color-name {};
  escape-string-regexp = callPackage ./escape-string-regexp {};
  fibers = callPackage ./fibers {};
  file-uri-to-path = callPackage ./file-uri-to-path {};
  has-flag = callPackage ./has-flag {};
  inflight = callPackage ./inflight {};
  minimist = callPackage ./minimist {};
  mkdirp = callPackage ./mkdirp {};
  npm4nix = callPackage ./npm4nix {};
  once = callPackage ./once {};
  parent-module = callPackage ./parent-module {};
  posix-getopt = callPackage ./posix-getopt {};
  resolve-from = callPackage ./resolve-from {};
  semver = callPackage ./semver {};
  wrappy = callPackage ./wrappy {};
}
